# Generated by Django 5.2 on 2025-05-08 17:46

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('color', models.CharField(default='#6c757d', max_length=7)),
            ],
            options={
                'verbose_name_plural': 'categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='flashcard',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AlterModelOptions(
            name='flashcardset',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AddField(
            model_name='flashcard',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'Łatwy'), ('medium', 'Średni'), ('hard', 'Trudny')], default='medium', max_length=6),
        ),
        migrations.AddField(
            model_name='flashcard',
            name='last_reviewed',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='flashcard',
            name='next_review',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='flashcard',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='flashcardset',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='flashcardset',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='flashcard',
            name='answer',
            field=models.TextField(validators=[django.core.validators.MinLengthValidator(5, 'Odpowiedź musi mieć co najmniej 5 znaków')]),
        ),
        migrations.AlterField(
            model_name='flashcard',
            name='question',
            field=models.TextField(validators=[django.core.validators.MinLengthValidator(10, 'Pytanie musi mieć co najmniej 10 znaków')]),
        ),
        migrations.AlterField(
            model_name='flashcardset',
            name='name',
            field=models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(3, 'Nazwa musi mieć co najmniej 3 znaki')]),
        ),
        migrations.AlterUniqueTogether(
            name='flashcardset',
            unique_together={('name', 'owner')},
        ),
        migrations.AddField(
            model_name='flashcard',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='flashcards.category'),
        ),
        migrations.AddField(
            model_name='flashcardset',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='flashcard_sets', to='flashcards.category'),
        ),
        migrations.AddField(
            model_name='flashcard',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='flashcards', to='flashcards.tag'),
        ),
        migrations.AddIndex(
            model_name='flashcard',
            index=models.Index(fields=['difficulty'], name='flashcards__difficu_6a638b_idx'),
        ),
        migrations.AddIndex(
            model_name='flashcard',
            index=models.Index(fields=['last_reviewed'], name='flashcards__last_re_cff5aa_idx'),
        ),
    ]
