# Generated by Django 4.2 on 2025-06-11 20:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('flashcards', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='flashcard',
            new_name='flashcards__difficu_6a638b_idx',
            old_name='flashcards__difficu_7c7c5c_idx',
        ),
        migrations.RenameIndex(
            model_name='flashcard',
            new_name='flashcards__last_re_cff5aa_idx',
            old_name='flashcards__last_r_3c4c5c_idx',
        ),
        migrations.RenameIndex(
            model_name='flashcard',
            new_name='flashcards__status_b7ef80_idx',
            old_name='flashcards__status_8c7c5c_idx',
        ),
        migrations.RenameIndex(
            model_name='flashcard',
            new_name='flashcards__due_dat_ba0364_idx',
            old_name='flashcards__due_dat_9c7c5c_idx',
        ),
        migrations.AlterField(
            model_name='flashcardset',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flashcard_sets', to=settings.AUTH_USER_MODEL),
        ),
    ]
