# Generated by Django 4.2 on 2025-06-10 18:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0003_flashcard_due_date_flashcard_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flashcard',
            name='answer',
            field=models.TextField(validators=[django.core.validators.MinLengthValidator(2, 'Odpowiedź musi mieć co najmniej 2 znaki')]),
        ),
        migrations.AlterField(
            model_name='flashcard',
            name='question',
            field=models.TextField(validators=[django.core.validators.MinLengthValidator(2, 'Pytanie musi mieć co najmniej 2 znaki')]),
        ),
    ]
