# Generated by Django 5.2 on 2025-05-08 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_is_2fa_enabled_user_otp_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_2fa_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
